/* Stefanny Arboleda 1152706891*/

/*PUNTO 1*/
/*PEGAR BASES DE DATOS*/
FILENAME REFFILE '/folders/myfolders/Bogota1.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=sav
	OUT=WORK.BOGOTA;
RUN;

FILENAME REFFILE '/folders/myfolders/Medellin.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=sav 
	OUT=WORK.MEDELLIN;
RUN;
		
FILENAME REFFILE '/folders/myfolders/Cali.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=sav 
	OUT=WORK.CALI;
RUN;
	
FILENAME REFFILE '/folders/myfolders/Barranquilla.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=sav 
	OUT=WORK.BARRANQUILLA;
RUN;

DATA BOGOTA1;
	SET BOGOTA;
	CIUDAD1=CIUDAD+0;
	DROP CIUDAD;
RUN;

DATA BOGOTA1;
	SET BOGOTA1;
	CIUDAD=CIUDAD1;
	DROP CIUDAD1;
RUN;

DATA TODAS;
 SET BARRANQUILLA CALI MEDELLIN BOGOTA1;
RUN;

/*CALCULAR NUEVA VARIABLE*/ 
DATA TODAS;
	SET TODAS;
	PAGADOLAR=PAGA*3416;
RUN;

/*VARIABLES CATEGORICAS*/

PROC FREQ DATA=TODAS;
	TABLES SEX CIUDAD HABITA;
RUN;

PROC FREQ DATA=TODAS ORDER=FREQ;
	TABLES SEX CIUDAD ESTUDIOS CENTRO / plots=freqplot;
RUN;

/*VARIABLES NUMERICAS*/

PROC UNIVARIATE DATA=TODAS;
	VAR PAGA NUMHER EDAD RENDESCO;
	HISTOGRAM / normal;
RUN;

/*RENDESCO POR HABITAT*/
data TODAS;
	SET TODAS;
	IF HABITA = 'R' THEN HABITANUM = 1;
	IF HABITA = 'U' THEN HABITANUM = 2;
RUN;
	
PROC UNIVARIATE DATA=TODAS;
	VAR RENDESCO;
	BY HABITANUM;
RUN;

/*PERCENTILES*/
PROC UNIVARIATE DATA=TODAS;
	VAR PAGA;
	OUTPUT OUT = PERCENTILES PCTLPTS= 50 75 95 PCTLPRE=PERCENTILES;
RUN;

/*PUNTO 2*/
/*RECODIFICACIÓN*/
DATA TODAS2;
	SET TODAS;
	IF 1 <= ESTUPADR <= 2 THEN ESTUPAD_REC = 'POCOS ESTUDIOS';
	IF 3 <= ESTUPADR <= 4 THEN ESTUPAD_REC= 'ESTUDIOS';
RUN;

/*VARIABLE OCIO NUEVA*/
DATA TODAS3;
	SET TODAS2;
	OCIOPROM = CINE + TEATRO + CONCIERT;
RUN;

PROC TABULATE DATA=TODAS3;
	VAR OCIOPROM;
	TABLE OCIOPROM*VAR;
RUN;

DATA TODAS4;
	SET  TODAS3;
	SEX_HABM = 0;
	IF HABITANUM = 2 AND SEX = 'H' THEN SEX_HABM = 0;
	IF HABITANUM = 1 AND SEX = 'H' THEN SEX_HABM = 1;
	ELSE IF SEX = 'M' THEN SEX_HABM = 2;
RUN;

/*PUNTO 3*/
/*LOS QUE SUPERAN LA MEDIA (Y)*/
PROC SQL;
CREATE TABLE INFO as SELECT mean(CINE) as PROMCINE,
						    mean(TEATRO) as PROMTEATRO,
							mean(CONCIERT) as PROMCONCIERT,
							1 as todos
							from TODAS4; 
QUIT;

data CONTADOR;
    do i = 1 to 295;
     TODOS=1;
     output;
     end;
run;

data CONTADOR;
	SET CONTADOR;
	DROP i;
RUN;

data TODAS4;
	MERGE TODAS4 CONTADOR;
RUN;

proc sort DATA=TODAS4;
	BY TODOS;
RUN;

DATA COND1;
	MERGE TODAS4 INFO; 
	BY TODOS;
RUN;
	
DATA TODAS4;
	SET COND1;
	IF CINE>PROMCINE and TEATRO>PROMTEATRO and CONCIERT>PROMCONCIERT 
	THEN SUPMED=1; ELSE SUPMED=0;
RUN;

PROC TABULATE DATA=TODAS4;
	VAR SUPMED;
	TABLE SUPMED*SUM;
RUN;

/*LOS QUE SUPERAN LA MEDIA (O)*/
DATA TODAS4;
	SET COND1;
	
DATA TODAS4;
	SET COND1;
	IF CINE>PROMCINE or TEATRO>PROMTEATRO or CONCIERT>PROMCONCIERT 
	THEN SUPMED=1; ELSE SUPMED=0;
RUN;

PROC TABULATE DATA=TODAS4;
	VAR SUPMED;
	TABLE SUPMED*SUM;
RUN;

/*ORDENARMIENTO*/
DATA CONT1;
	DO i = 1 to 295;
    output;
    END;
RUN;

DATA TODAS4;
	MERGE CONT1 TODAS4;
RUN;

PROC SORT DATA=TODAS4;
	BY SEX NIVSOC;
RUN;
	
PROC SORT DATA=TODAS4; /*NÚMERO DE SUJETO 55*/
	BY i;
RUN;

/*PAGA MAYORES DE EDAD*/
DATA TODAS4;
	SET TODAS4;
	IF EDAD > 18 THEN PAGMAY = 1; ELSE PAGMAY = 0;
RUN;

PROC SORT DATA=TODAS4;
	BY PAGMAY;
QUIT;

PROC UNIVARIATE DATA=TODAS4;
	VAR PAGA;
	BY PAGMAY;
RUN;

/*PUNTO 4*/
PROC TABULATE DATA=TODAS4;
	CLASS SEX HABITA CENTRO ESTUDIOS;
	VAR PAGA;
	TABLE SEX*HABITA*ESTUDIOS ALL, CENTRO ALL;
RUN;

PROC TABULATE DATA=TODAS4;
	CLASS SEX HABITA ESTUPADR ESTUDIOS;
	VAR PAGA;
	TABLE SEX*HABITA*ESTUDIOS ALL, ESTUPADR ALL;
RUN;

PROC TABULATE DATA=TODAS4;
	CLASS SEX ESTUPADR ESTUDIOS;
	VAR PAGA;
	TABLE SEX*ESTUDIOS ALL, ESTUPADR ALL;
RUN;

/*GRÁFICO*/
ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=TODAS;
	scatter x=tv y=libro /;
	xaxis grid;
	yaxis grid;
run;

ods graphics / reset;

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=TODAS;
	scatter x=cine y=libro /;
	xaxis grid;
	yaxis grid;
run;

ods graphics / reset;
